version: '3.8'

services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5433:5432"   # host:container (optional; use only if you want to connect from host)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
           python manage.py collectstatic --noinput &&
           gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      IS_PRODUCTION: 'false'  # Explicitly set to false for local development

volumes:
  postgres_data:
