openapi: 3.0.3
info:
  title: Online Polls API
  description: API documentation for the Online Polls system built with Django.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/api
    description: Local development server

paths:
  /polls/:
    get:
      summary: List all polls
      tags:
        - Polls
      responses:
        "200":
          description: A list of polls
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Poll"
    post:
      summary: Create a new poll
      tags:
        - Polls
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PollCreate"
      responses:
        "201":
          description: Poll created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Poll"

  /polls/{pollId}/:
    get:
      summary: Get details of a poll
      tags:
        - Polls
      parameters:
        - name: pollId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Poll details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Poll"

  /polls/{pollId}/choices/:
    get:
      summary: List choices for a poll
      tags:
        - Choices
      parameters:
        - name: pollId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Choices for the poll
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Choice"
    post:
      summary: Add a choice to a poll
      tags:
        - Choices
      parameters:
        - name: pollId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChoiceCreate"
      responses:
        "201":
          description: Choice created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Choice"

  /polls/{pollId}/vote/:
    post:
      summary: Cast a vote for a choice
      tags:
        - Votes
      parameters:
        - name: pollId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                choice_id:
                  type: integer
      responses:
        "200":
          description: Vote cast successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vote"

components:
  schemas:
    Poll:
      type: object
      properties:
        id:
          type: integer
        question:
          type: string
        created_at:
          type: string
          format: date-time
    PollCreate:
      type: object
      required:
        - question
      properties:
        question:
          type: string
    Choice:
      type: object
      properties:
        id:
          type: integer
        poll_id:
          type: integer
        choice_text:
          type: string
        votes:
          type: integer
    ChoiceCreate:
      type: object
      required:
        - choice_text
      properties:
        choice_text:
          type: string
    Vote:
      type: object
      properties:
        choice_id:
          type: integer
        poll_id:
          type: integer
        timestamp:
          type: string
          format: date-time
